"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./i18n";
import { useEffect } from "react";
import { useTranslation } from "react-i18next";
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
   const { i18n, t } = useTranslation();

  useEffect(() => {
    document.documentElement.lang = i18n.language;
    document.documentElement.dir = i18n.language === "ar" ? "rtl" : "ltr";
  }, [i18n.language]);

  const switchLanguage = (lang) => {
    i18n.changeLanguage(lang);
  };

  return (
    <html><head>
<style>
@import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap');
</style>
</head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="navbar ">
        <div className="navbar-bg"></div>
          <h1 className="logo">{t("app_title")}</h1>
          <div className="lang-toggle">
            <button className="language-btn" onClick={() => switchLanguage("en")}>En</button>
            <button className="language-btn" onClick={() => switchLanguage("ar")}>AR</button>
          </div>
        </header>
        <div>
        {children}
        </div>
      </body>
    </html>
  );
}
